In [1]:
import numpy as np
import pandas as pd

In [2]:
hotdog = pd.read_csv('Hotdog Survey.csv')

hotdog.head()

,Timestamp,Year at UVA,What is your Gender Identity?,What Schools are you a Part of?,Is a Hotdog a Sandwich?,How strongly do you feel about your previous answer?,How frequently do you eat hot dogs?
0,1/14/2026 13:51:45,Graduate Student,Man,Data Science,Yes,1,Never
1,1/14/2026 13:53:31,3rd Year,Woman,Engineering,Yes,3,Never
2,1/14/2026 13:53:35,3rd Year,Woman,"Arts and Sciences, Engineering",Yes,1,Never
3,1/14/2026 13:55:42,4th Year,Woman,Engineering,No,4,Never
4,1/14/2026 13:57:21,4th Year,Woman,Engineering,Yes,5,Occassionally (ex. once every few months)

In [3]:
# rename columns for easier access
names = ['timestamp','year','gender','hotdog_opinion','opinion_strength','consumption_freq']
hotdog.rename(columns={'Timestamp': 'timestamp',
                       'Year at UVA': 'year',
                       'What is your Gender Identity?': 'gender',
                       'Is a Hotdog a Sandwich?': 'hotdog_opinion',
                       'How strongly do you feel about your previous answer?': 'opinion_strength',
                       'How frequently do you eat hot dogs?': 'consumption_freq'}, inplace=True)

hotdog.head()

,timestamp,year,gender,What Schools are you a Part of?,hotdog_opinion,opinion_strength,consumption_freq
0,1/14/2026 13:51:45,Graduate Student,Man,Data Science,Yes,1,Never
1,1/14/2026 13:53:31,3rd Year,Woman,Engineering,Yes,3,Never
2,1/14/2026 13:53:35,3rd Year,Woman,"Arts and Sciences, Engineering",Yes,1,Never
3,1/14/2026 13:55:42,4th Year,Woman,Engineering,No,4,Never
4,1/14/2026 13:57:21,4th Year,Woman,Engineering,Yes,5,Occassionally (ex. once every few months)

In [5]:
# performs one-sample z-test
# H0: p = 0.25 vs H1: p != 0.25

p0 = 0.25  # null hypothesis proportion
n = hotdog.shape[0]  # sample size
SE = np.sqrt(p0 * (1 - p0) / n)  # standard error
p_hat = (hotdog['hotdog_opinion'] == 'Yes').mean()  # sample proportion
z = (p_hat - p0) / SE  # z-score

# find p-value from z-score for two-tailed test
import scipy.stats as stats
p_value = 2 * (1 - stats.norm.cdf(abs(z)))
print(f'Z-score: {z}, P-value: {p_value}')

Z-score: 4.607392991208651, P-value: 4.077489221598896e-06

p < 0.05 therefore null hypothesis is rejected and alternative hypothesis is accepted. The proportion of UVA undergraduate students who believe a hotdog is a sandwich is not 25% with 95% significance.