### Project 0: Analysis of Hot Dog Surevey Results

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Hotdog Survey (Responses) - Form Responses 1.csv')
df.head(20)

,Timestamp,Year at UVA,What is your Gender Identity?,What Schools are you a Part of?,Is a Hotdog a Sandwich?,How strongly do you feel about your previous answer?,How frequently do you eat hot dogs?
0,1/14/2026 13:51:45,Graduate Student,Man,Data Science,Yes,1,Never
1,1/14/2026 13:53:31,3rd Year,Woman,Engineering,Yes,3,Never
2,1/14/2026 13:53:35,3rd Year,Woman,"Arts and Sciences, Engineering",Yes,1,Never
3,1/14/2026 13:55:42,4th Year,Woman,Engineering,No,4,Never
4,1/14/2026 13:57:21,4th Year,Woman,Engineering,Yes,5,Occassionally (ex. once every few months)
5,1/14/2026 13:57:30,4th Year,Man,"Engineering, Data Science",Yes,3,Occassionally (ex. once every few months)
6,1/14/2026 13:58:13,4th Year,Woman,"Engineering, Data Science",Yes,4,Never
7,1/14/2026 14:00:55,3rd Year,Man,"Arts and Sciences, Engineering, Data Science",No,4,Occassionally (ex. once every few months)
8,1/14/2026 14:05:33,3rd Year,Woman,Engineering,Yes,4,Occassionally (ex. once every few months)
9,1/14/2026 14:05:46,Graduate Student,Man,Engineering,No,4,Rarely (ex. once a year)
10,1/14/2026 14:07:37,2nd Year,Man,Engineering,Yes,4,Occassionally (ex. once every few months)
11,1/14/2026 14:08:22,4th Year,Man,Engineering,No,2,Occassionally (ex. once every few months)
12,1/14/2026 14:08:25,Graduate Student,Man,Engineering,No,4,Occassionally (ex. once every few months)
13,1/14/2026 14:10:13,1st Year,Woman,Engineering,Yes,3,Occassionally (ex. once every few months)
14,1/14/2026 14:10:51,1st Year,Woman,Education,No,3,Rarely (ex. once a year)
15,1/14/2026 14:12:58,3rd Year,Man,Arts and Sciences,No,4,Occassionally (ex. once every few months)
16,1/14/2026 14:13:55,4th Year,Man,Arts and Sciences,No,4,Occassionally (ex. once every few months)
17,1/14/2026 14:15:00,Graduate Student,Man,Law,No,4,Never
18,1/14/2026 14:16:18,3rd Year,Man,Engineering,No,5,Frequently (ex. multiple times a month)
19,1/14/2026 14:17:15,4th Year,Woman,McIntire School of Commerce,Yes,5,Rarely (ex. once a year)

In [3]:
# Remove Graduate Students and Other/Not Affiliated
df = df[~df['Year at UVA'].isin(['Graduate Student', 'Other/Not Affiliated'])]
df.head(20)

,Timestamp,Year at UVA,What is your Gender Identity?,What Schools are you a Part of?,Is a Hotdog a Sandwich?,How strongly do you feel about your previous answer?,How frequently do you eat hot dogs?
1,1/14/2026 13:53:31,3rd Year,Woman,Engineering,Yes,3,Never
2,1/14/2026 13:53:35,3rd Year,Woman,"Arts and Sciences, Engineering",Yes,1,Never
3,1/14/2026 13:55:42,4th Year,Woman,Engineering,No,4,Never
4,1/14/2026 13:57:21,4th Year,Woman,Engineering,Yes,5,Occassionally (ex. once every few months)
5,1/14/2026 13:57:30,4th Year,Man,"Engineering, Data Science",Yes,3,Occassionally (ex. once every few months)
6,1/14/2026 13:58:13,4th Year,Woman,"Engineering, Data Science",Yes,4,Never
7,1/14/2026 14:00:55,3rd Year,Man,"Arts and Sciences, Engineering, Data Science",No,4,Occassionally (ex. once every few months)
8,1/14/2026 14:05:33,3rd Year,Woman,Engineering,Yes,4,Occassionally (ex. once every few months)
10,1/14/2026 14:07:37,2nd Year,Man,Engineering,Yes,4,Occassionally (ex. once every few months)
11,1/14/2026 14:08:22,4th Year,Man,Engineering,No,2,Occassionally (ex. once every few months)
13,1/14/2026 14:10:13,1st Year,Woman,Engineering,Yes,3,Occassionally (ex. once every few months)
14,1/14/2026 14:10:51,1st Year,Woman,Education,No,3,Rarely (ex. once a year)
15,1/14/2026 14:12:58,3rd Year,Man,Arts and Sciences,No,4,Occassionally (ex. once every few months)
16,1/14/2026 14:13:55,4th Year,Man,Arts and Sciences,No,4,Occassionally (ex. once every few months)
18,1/14/2026 14:16:18,3rd Year,Man,Engineering,No,5,Frequently (ex. multiple times a month)
19,1/14/2026 14:17:15,4th Year,Woman,McIntire School of Commerce,Yes,5,Rarely (ex. once a year)
20,1/14/2026 14:21:42,3rd Year,Man,"Arts and Sciences, McIntire School of Commerce",Yes,2,Occassionally (ex. once every few months)
21,1/14/2026 14:22:31,4th Year,Woman,Arts and Sciences,Yes,5,Occassionally (ex. once every few months)
22,1/14/2026 14:23:06,3rd Year,Man,McIntire School of Commerce,Yes,1,Rarely (ex. once a year)
23,1/14/2026 14:24:06,1st Year,Man,Arts and Sciences,No,4,Rarely (ex. once a year)

In [4]:
df['Is a Hotdog a Sandwich?'].value_counts()

Is a Hotdog a Sandwich?
No     104
Yes     71
Name: count, dtype: int64

In [6]:
yes = 71 / (104+71)
print("Yes: ", yes*100, "%")

Yes:  40.57142857142857 %

In [7]:
no = 104 / (104+71)
print("No: ", no*100, "%")

No:  59.42857142857143 %

In [12]:
import math
p_minus_p_0 = (71/175) - (25/100)
sqr_root = math.sqrt((.25*(1-.25)/175))
z = p_minus_p_0 / sqr_root
print("Z-Score: ", z)

Z-Score:  4.7571500071446335

z-score: 4.7571500071446335

p-value: 0